import type { CompanyConfig } from './types';

export const COMPANIES: CompanyConfig[] = [
  { id: 'Adriana Posto Campo Velho', name: 'Adriana Posto Campo Velho', pricePerUnit: 20.00 },
  { id: 'Alicerce', name: 'Alicerce', pricePerUnit: 18.00 },
  { id: 'Amanda Prime', name: 'Amanda Prime', pricePerUnit: 18.00 },
  { id: 'Ana Cláudia Copa Executivo', name: 'Copa Executivo', pricePerUnit: 18.00 },
  { id: 'Anpliato N8', name: 'Anpliato N8', pricePerUnit: 20.00 },
  { id: 'Anpliato N9', name: 'Anpliato N9', pricePerUnit: 23.00 },
  { id: 'Beth', name: 'Beth', pricePerUnit: 18.00 },
  { id: 'Big Master N8', name: 'Big Master N8', pricePerUnit: 20.00 },
  { id: 'Big Master N9', name: 'Big Master N9', pricePerUnit: 23.00 },
  { id: 'Bill H. Prime', name: 'Bill H. Prime', pricePerUnit: 18.00 },
  { id: 'Boldrin (Particular Prime)', name: 'Boldrin (Praticular Prime)', pricePerUnit: 18.00 },
  { id: 'Boldrin Prime', name: 'Boldrin Prime', pricePerUnit: 18.00 },
  { id: 'Bruno Honorato Prime', name: 'Bruno Honorato Prime', pricePerUnit: 18.00 },
  { id: 'Caio Notalize', name: 'Caio Notalize', pricePerUnit: 18.00 },
  { id: 'Cláudio', name: 'Cláudio', pricePerUnit: 18.00 },
  { id: 'Cris Soled', name: 'Cris Soled', pricePerUnit: 20.00 },
  { id: 'CS Ar Condiciondo Marmita', name: 'CS Ar Condiciondo Marmita', pricePerUnit: 18.00 },
  { id: 'CS Ar Condiciondo PF', name: 'CS Ar Condiciondo PF', pricePerUnit: 25.00 },
  { id: 'Dennis Águas', name: 'Dennis Águas', pricePerUnit: 18.00 },
  { id: 'Dismafe', name: 'Dismafe', pricePerUnit: 18.00 },
  { id: 'Estefani Copa Executivo', name: 'Estefani Copa Executivo', pricePerUnit: 18.00 },
  { id: 'Greyce Prime', name: 'Greyce Prime', pricePerUnit: 18.00 },
  { id: 'Gustavo Alecio Prime', name: 'Gustavo Alecio Prime', pricePerUnit: 18.00 },
  { id: 'Julio Docinho', name: 'Julio Docinho', pricePerUnit: 20.00 },
  { id: 'Kae Notalize', name: 'Kae Notalize', pricePerUnit: 18.00 },
  { id: 'Kamila Prime', name: 'Kamila Prime', pricePerUnit: 18.00 },
  { id: 'Kil Águas', name: 'Kil Águas', pricePerUnit: 18.00 },
  { id: 'Léo Escola Videira', name: 'Léo Escola Videira', pricePerUnit: 19.00 },
  { id: 'Márcia Gomes Ciap', name: 'Márcia Gomes Ciap', pricePerUnit: 20.00 },
  { id: 'Marcio Bellcar', name: 'Marcio Bellcar', pricePerUnit: 18.00 },
  { id: 'Maria Neuza', name: 'Maria Neuza', pricePerUnit: 20.00 },
  { id: 'Melhor Aroma Marmita', name: 'Melhor Aroma Marmita', pricePerUnit: 18.00 },
  { id: 'Melhor Aroma PF', name: 'Melhor Aroma PF', pricePerUnit: 25.00 },
  { id: 'Nicolly Escola Videira', name: 'Nicolly Escola Videira', pricePerUnit: 19.00 },
  { id: 'Nilmara (trabalha com o Zico)', name: 'Nilmara (trabalha com o Zico)', pricePerUnit: 20.00 },
  { id: 'Patricia (Particular)', name: 'Patrícia (Particular)', pricePerUnit: 20.00 },
  { id: 'Paulo Vicente Prime', name: 'Paulo Vicente Prime', pricePerUnit: 18.00 },
  { id: 'Puríssima', name: 'Puríssima', pricePerUnit: 22.00 },
  { id: 'Renata Roda Matriz N8', name: 'Roda Matriz N8', pricePerUnit: 18.00 },
  { id: 'Roda Matriz N9', name: 'Roda Matriz N9', pricePerUnit: 19.00 },
  { id: 'SG Funilaria', name: 'SG Funilaria', pricePerUnit: 18.00 },
  { id: 'SG Petrópolis a parte', name: 'SG Petrópolis a parte', pricePerUnit: 18.00 },
  { id: 'Soraia', name: 'Soraia (Particular Roda Motriz)', pricePerUnit: 18.00 },
  { id: 'Studio', name: 'Studio', pricePerUnit: 18.00 },
  { id: 'Sul Tintas Marmita', name: 'Sul Tintas Marmita', pricePerUnit: 18.00 },
  { id: 'Sul Tintas PF', name: 'Sul Tintas PF', pricePerUnit: 25.00 },
  { id: 'Thalyssa Mercadão', name: 'Thayllisa Mercadão', pricePerUnit: 18.00 },
  { id: 'Thaynara Godinho Prime', name: 'Thaynara Godinho Prime', pricePerUnit: 18.00 },
  { id: 'Tiago Mecânico', name: 'Tiago Mecânico', pricePerUnit: 20.00 },
  { id: 'Todimo', name: 'Todimo PF', pricePerUnit: 22.00 },
  { id: 'Videira Marmita', name: 'Videira Marmita', pricePerUnit: 18.00 },
  { id: 'Videira PF', name: 'Videira PF', pricePerUnit: 25.00 },
  { id: 'Wellington Notalize (Família)', name: 'Wellington Notalize (Família)', pricePerUnit: 60.00 },
  { id: 'Wesley Mercadão', name: 'Wesley Mercadão', pricePerUnit: 18.00 },
  { id: 'Zico Mecânico', name: 'Zico Mecânico', pricePerUnit: 20.00 },
];
