import type { CompanyConfig } from './types';

export const COMPANIES: CompanyConfig[] = [
  {id: 'Marmita avulsa N8', name: 'Marmita avulsa N8', pricePerUnit: 20.00 },
  {id: 'Marmita avulsa N9', name: 'Marmita avulsa N9', pricePerUnit: 23.00 },
  { id: 'funcionario', name: 'Funcionário (Vale)', pricePerUnit: 17.00 },
  { id: 'Todimo', name: 'Todimo PF', pricePerUnit: 22.00 },
  { id: 'Videira Marmita', name: 'Videira Marmita', pricePerUnit: 18.00 },
  { id: 'Videira PF', name: 'Videira PF', pricePerUnit: 30.00 },
  { id: 'Sul Tintas Marmita', name: 'Sul Tintas Marmita', pricePerUnit: 18.00 },
  { id: 'Sul Tintas PF', name: 'Sul Tintas PF', pricePerUnit: 22.00 },
  { id: 'Dismafe', name: 'Dismafe', pricePerUnit: 18.00 },
  { id: 'Cláudio', name: 'Cláudio', pricePerUnit: 18.00 },
  { id: 'Melhor Aroma Marmita', name: 'Melhor Aroma Marmita', pricePerUnit: 18.00 },
  { id: 'Melhor Aroma PF', name: 'Melhor Aroma PF', pricePerUnit: 22.00 },
  { id: 'Puríssima', name: 'Puríssima', pricePerUnit: 22.00 },
  { id: 'Mercadão', name: 'Mercadão', pricePerUnit: 18.00 },
  { id: 'Prime', name: 'Prime', pricePerUnit: 18.00 },
  { id: 'Roda Matriz N8', name: 'Roda Matriz N8', pricePerUnit: 18.00 },
  { id: 'Roda Matriz N9', name: 'Roda Matriz N9', pricePerUnit: 19.00 },
  { id: 'Alicerce', name: 'Alicerce', pricePerUnit: 18.00 },
  { id: 'Notalize', name: 'Notalize', pricePerUnit: 18.00 },
  { id: 'Studio', name: 'Studio', pricePerUnit: 18.00 },
  { id: 'SG Funilaria', name: 'SG Funilaria', pricePerUnit: 18.00 },
  { id: 'Strobel', name: 'Strobel', pricePerUnit: 18.00 },
  { id: 'CS Ar Condiciondo Marmita', name: 'CS Ar Condiciondo Marmita', pricePerUnit: 18.00 },
  { id: 'CS Ar Condiciondo PF', name: 'CS Ar Condiciondo PF', pricePerUnit: 25.00 },
];
